services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: pluralsight
      POSTGRES_PASSWORD: pluralsight
    ports:
      - 5432:5432

